# Generated by Django 4.2.6 on 2023-10-26 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='photo',
        ),
        migrations.CreateModel(
            name='CompanyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company_photos/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dawrni_app.company')),
            ],
        ),
    ]
