# Generated by Django 4.2.6 on 2023-10-26 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0003_alter_company_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dawrni_app.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_certified',
            field=models.BooleanField(default=False, verbose_name='Is Certified'),
        ),
        migrations.AlterField(
            model_name='company',
            name='licence',
            field=models.CharField(max_length=255, verbose_name='Licence'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
