# Generated by Django 4.2.6 on 2023-10-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0005_remove_company_about_remove_company_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='client',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='about_ar',
            field=models.TextField(blank=True, null=True, verbose_name='About (Arabic)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='about_en',
            field=models.TextField(verbose_name='About (English)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Address (Arabic)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_en',
            field=models.TextField(verbose_name='Address (English)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Name (English)'),
        ),
    ]
